python debias.py \
    --data_dir ./data/debias/ \
    --debias_type gender \
    --divergence_dim 1 \
    --model_name_or_path bert-base-uncased \
    --output_dir ./out/ \
    --run_name run00 \
    --prompt_dir ./data/prompts_bert-base-uncased_gender.txt \
    --num_gpus 1 \
    --per_device_batch_size 16 \
    --dataloader_num_workers 1 \
    --learning_rate 1e-5 \
    --num_train_epochs 5
